version: "3"

services:
  baserow:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
      - redis
    environment:
      - BASEROW_PUBLIC_URL=http://mskwo0gws0c8owwsswkc0c0k.104.37.187.180.sslip.io
      - BASEROW_CADDY_ADDRESSES=:80
      - DJANGO_SETTINGS_MODULE=baserow.config.settings.base
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/baserow
      - REDIS_URL=redis://redis:6379

  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=baserow
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
